
select*from fact
select*from product
select*from Location
 
1. Display the number of states present in theLocationTable
select count(distinct state) as numberofstates 
from location

2. How many products are of regular type?
select count(type)
from product where type='regular'

3. How much spending has been done on marketing of product ID1?
select count (marketing) from fact where productid=1

4. What is the minimum sales of a product?
select min (sales)from fact

5. Display the max Cost of Good Sold (COGS).
select max(cogs)from fact

6. Display the details of the product where product type iscoffee.
select*from product where product_type='coffee'

7. Display the details where total expenses are greater than40.
select*from fact where Total_Expenses>40

8. What is the average sales in area code 719?
select avg(sales)from fact where Area_Code=719

9. Find out the total profit generated by Colorado state.
select state, sum(profit) as profit from fact as f  join location as l  on f.Area_Code=L.Area_Code group by state
having state='colorado'

10.Display the average inventory for each product ID.
select productid,avg(Inventory) as avg_inventory from fact group by ProductId order by ProductId

11. Display state in a sequential order in a LocationTable
 select distinct(state) from Location order by state

12. Display the average budget of the Product where the average budget margin should be greater than 100.
select avg(budget_margin) from fact group by budget_margin
having avg(budget_margin)>100

13.What is the total sales done on date 2010-01-01?
select sum(sales) from fact where date='2010-01-01'

14. Display the average total expense of each product ID on anindividual date.
select date,ProductId,avg(total_expenses) as totalexpense from fact group by productid, date order by ProductId asc,date desc

15. Display the table with the following attributes such as date, productID,
 product_type, product, sales, profit, state, area_code.
 select f.date,f.productid,f.sales,f.profit,f.area_code,p.product_type,p.product,l.state from fact as f join Product as p on f.ProductId=p.ProductId
 join Location as l on l.Area_Code=f.Area_Code

 16.Display the rank without any gap to show the sales wiserank.
  select *, rank()over(order by sales)as saleswise_rank from fact

 17.Find the state wise profit and sales.
 select l.state,sum(f.profit)as profit,sum(f.sales)as sales from Location as l join fact as f on l.Area_Code=f.Area_Code group by l.state

 18. Find the state wise profit and sales along with the productname.
 select l.state,p.product,sum(f.profit)as profit,sum(f.sales)as sales from Location as l join fact as f on l.Area_Code=f.Area_Code
 join Product as p on p.ProductId=f.ProductId group by l.State,p.Product 
   
 19.If there is an increase in sales of 5%, calculate the increasedsales.
  select sales ,sales*1.05 as increased_sales from fact

 20. Find the maximum profit along with the product ID and producttype
select p.Product_Type,f.productid,max(f.profit)as maxprofit from fact as f join product as p on f.ProductId=p.ProductId group by p.Product_Type,f.ProductId 
order by maxprofit desc

21. Create a stored procedure to fetch the result according to theproduct type from ProductTable.
 create procedure usp_result
 (
 @producttype varchar(50)
 )
 as
 begin
 
 select * from Product where Product_Type=@producttype
 end
 
 execute usp_result 'coffee'

 22. Write a query by creating a condition in which if the total expenses isless than
 60 then it is a profit or else loss.
 select *, profit_cloumn=
 case
 when total_expenses< 60 then 'profit'
 else 'loss'
 end
  from fact
  
23. Give the total weekly sales value with the date and product IDdetails. Use
 roll-up to pull the data in hierarchical order
 select date,datepart(week,date) as sales_week, sum(sales) as total_weeklysales,productid from fact group by  rollup(date,datepart(week,date),ProductId)
 order by date,datepart(week,date),ProductId
 
 24.Apply union and intersection operator on the tables which consistof
 attribute area code.

 select Area_Code  from fact 
 union
 select Area_Code from Location

 select area_code from fact
 intersect
 select area_code from location

 25.Create a user-defined function for the product table to fetch a particular product type based upon the user’s preference
 create function udf_product
 (
 @product_type varchar(50)
 )
 returns table
 as
 return
 (
 select * from Product where product_type=@product_type
 )    
 
 select * from dbo.udf_product('herbal tea')

 26.change the product type from coffee to tea where productid 1 and undo it

 begin transaction
 update product set Product_Type='tea' where ProductId=1 and Product_Type='coffee'
 rollback transaction

 select*from Product

 27. Display the date, product ID and sales where total expenses are between 100 to 200.
  select date,productid,sales,Total_Expenses 
  from fact 
  where Total_Expenses between 100 and 200
 
 28. Delete the records in the Product Table for regulartype.

 delete from Product 
 where type='regular'

 select*from Product

 29. Display the ASCII value of the fifth character from the columnProduct.

select ASCII(SUBSTRING(Product, 5, 1)) as ASCII_Value
from Product

